name: SecureCloud
options:
  bundleIdPrefix: com.securecloud
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16"
  generateEmptyDirectories: true
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    PRODUCT_NAME: SecureCloud
    SWIFT_VERSION: 5.10
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    TARGETED_DEVICE_FAMILY: 1
    ENABLE_PREVIEWS: YES
    SWIFT_STRICT_CONCURRENCY: complete
    CLANG_ENABLE_MODULES: YES
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    INFOPLIST_FILE: SecureCloud/Resources/Info.plist
    CODE_SIGN_ENTITLEMENTS: SecureCloud/Resources/SecureCloud.entitlements
    SWIFT_EMIT_LOC_STRINGS: YES
  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: dwarf
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      SWIFT_OPTIMIZATION_LEVEL: "-O"

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.0.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 7.10.0

targets:
  SecureCloud:
    type: application
    platform: iOS
    sources:
      - path: SecureCloud
        excludes:
          - Tests/**
    resources:
      - path: SecureCloud/Resources
    dependencies:
      - package: GRDB
        product: GRDB
      - package: Kingfisher
        product: Kingfisher
    info:
      path: SecureCloud/Resources/Info.plist
      properties:
        CFBundleName: SecureCloud
        CFBundleDisplayName: SecureCloud
        CFBundleIdentifier: com.securecloud.vault
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        LSRequiresIPhoneOS: true
        UIRequiresFullScreen: true
        UIStatusBarStyle: UIStatusBarStyleDefault
        NSFaceIDUsageDescription: "SecureCloud uses Face ID to unlock your encrypted vault."
        UILaunchScreen:
          UIColorName: LaunchBackground
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - fetch
          - processing
        BGTaskSchedulerPermittedIdentifiers:
          - com.securecloud.vault.sync
        UIAppFonts:
          - Inter-Regular.ttf
          - Inter-Medium.ttf
          - Inter-SemiBold.ttf
          - Inter-Bold.ttf
    entitlements:
      path: SecureCloud/Resources/SecureCloud.entitlements
      properties:
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.securecloud.vault
        com.apple.developer.associated-domains: []

  SecureCloudTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SecureCloud/Tests/UnitTests
    dependencies:
      - target: SecureCloud
    settings:
      base:
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/SecureCloud.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/SecureCloud

  SecureCloudUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SecureCloud/Tests/UITests
    dependencies:
      - target: SecureCloud
